import 'bootstrap/dist/css/bootstrap.min.css';
import React, { useState, useEffect } from 'react';
import { FaDownload } from 'react-icons/fa';
import { Row, Col, Card, Table } from 'react-bootstrap';
import logo from '../../assets/gree_documentlogo.png';
import Spinner from 'react-bootstrap/Spinner';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';

const SalesReport = () => {

  const [quotations, setQuotations] = useState([])

    useEffect(() => {
      const fetchData = async () => {
          try {
              const response = await axios.get('http://localhost:4000/api/getQuotations/')
              setQuotations(response.data)
          } catch (error) {
              console.error('Error fetching data: ', error)
          }
      }
      fetchData()
    }, [])

    const navigate = useNavigate()

    const [validated, setValidated] = useState(false);
    const [preview, setPreview] = useState(false);
    const [loader, setLoader] = useState(false);
    const [totalSum, setTotalSum] = useState(null)
    const [checkDl, setCheckDl] = useState(true)
    //const [address, setAddress] = useAddressString(quotations)

    const downloadPDF = () => {
      const capture1 = document.querySelector('.quotation-file');
      const capture2 = document.querySelector('.quotations-file');
    
      setLoader(true);
    
      Promise.all([
        html2canvas(capture1, { scale: 2 })
      ]).then((canvases) => {
        const imgData1 = canvases[0].toDataURL('image/png');
    
        const doc = new jsPDF('p', 'in', 'letter');
        const imgWidth = 8.5;
        const imgHeight = 11;
    
        doc.addImage(imgData1, 'PNG', 0, 0, imgWidth, imgHeight);
    
        setLoader(false);
        doc.save('quotation.pdf');
      });
    };

    const handleSubmit = () => {
        if (checkDl) { downloadPDF() }
    }

 
    
    
    return (
        <div style={{ width: '100%', padding: '20px', background: '#E5EDF4', color: '#014c91'}}>
            <h1>Preview Generated Report</h1>
            <h5>View or download generated report</h5>
            <hr style={{ width: '100%', marginTop: '10px', marginBottom: '10px' }} />

            <Card className="quotation-file" style={{ width: '8.5in', height: '11in', padding: '0.5in' }}>
            <Row>
                <Col lg="7">
                  <img src={logo} style={{ width: '100%', height: 'auto', opacity: '1', paddingBottom: '7px' }} alt="Banner" />
                </Col>
                <Col lg="5" style={{ textAlign: 'right' }}>
                    <h1 className="me-2" style={{ fontFamily: 'Cambria', color: '#0070c0', fontSize: '2em', fontWeight: 'bold' }}>SALES REPORT</h1>
                </Col>
            </Row>
                <Table style={{ fontSize:"13px", borderCollapse: 'collapse', width: '100%', border: 'none' }}>
                    <tbody>
                        <tr>
                            <td colSpan="4" style={{ padding: '0', border: 'none'}}>Generated on<strong> 09-Feb-24 12:00 PM</strong> </td> 
                        </tr>
                        <tr>
                            <td colSpan="4" style={{ padding: '0', border: 'none'}}>Generated by <strong>Miguel Perez</strong> </td> 
                        </tr>
                        <tr>
                            <td colSpan="4" style={{ padding: '0', border: 'none'}}>Period Covered: <strong>01-Apr-2024 to 31-Apr-2024</strong> </td> 
                        </tr>

                        <tr style={{ height: '10px' }}></tr> 
                        
                        <tr >
                          <td colSpan="4" style={{ padding: '0', border: '1px solid black', color: 'white', background: '#082464', textAlign: 'center' }}>
                              <strong>Sales Overview </strong>
                          </td>
                        </tr>

                        <tr>
                            <td colSpan="3" style={{ padding: '3px', border: '1px solid black'}}>Total Sales Revenue </td>
                            <td colSpan="1" style={{ padding: '3px', border: '1px solid black', textAlign: 'right' }}>Php 100,000.00</td>  
                        </tr>
                        <tr>
                            <td colSpan="3" style={{ padding: '3px', border: '1px solid black'}}>Sales Growth (vs. Last 30 Days)</td>
                            <td colSpan="1" style={{ padding: '3px', border: '1px solid black', textAlign: 'right' }}>+15.38%</td>  
                        </tr>

                        <tr style={{ height: '10px' }}></tr> 

                        <tr >
                          <td colSpan="4" style={{ padding: '3px', border: '1px solid black', color: 'white', background: '#082464', textAlign: 'center' }}>
                              <strong>Window-Type Products Breakdown </strong>
                          </td>
                        </tr>
                        <tr>
                            <td style={{ padding: '3px', border: '1px solid black', width: '50%'}}>Window-Type Product</td>  
                            <td style={{ padding: '3px', border: '1px solid black', textAlign: 'center', width: '12%' }}>Units Sold</td>  
                            <td style={{ padding: '3px', border: '1px solid black', textAlign: 'center', width: '23%' }}>Average Selling Price</td>
                            <td style={{ padding: '3px', border: '1px solid black', textAlign: 'center', width: '15%'}}>Revenue</td>  
                        </tr>

                        <tr style={{ height: '10px' }}></tr> 

                        <tr >
                          <td colSpan="4" style={{ padding: '3px', border: '1px solid black', color: 'white', background: '#082464', textAlign: 'center' }}>
                              <strong>Split-Type Products Breakdown</strong>
                          </td>
                        </tr>
                        <tr>
                            <td style={{ padding: '3px', border: '1px solid black', width: '50%'}}>Split-Type Product</td>  
                            <td style={{ padding: '3px', border: '1px solid black', textAlign: 'center', width: '12%' }}>Units Sold</td>  
                            <td style={{ padding: '3px', border: '1px solid black', textAlign: 'center', width: '23%' }}>Average Selling Price</td>
                            <td style={{ padding: '3px', border: '1px solid black', textAlign: 'center', width: '15%'}}>Revenue</td>  
                        </tr>

                        <tr style={{ height: '10px' }}></tr> 

                        <tr >
                          <td colSpan="4" style={{ padding: '3px', border: '1px solid black', color: 'white', background: '#082464', textAlign: 'center' }}>
                              <strong>Services Rendered Breakdown </strong>
                          </td>
                        </tr>
                        <tr>
                            <td style={{ padding: '3px', border: '1px solid black', width: '50%'}}>Service</td>  
                            <td style={{ padding: '3px', border: '1px solid black', textAlign: 'center', width: '12%' }}>Units Sold</td>  
                            <td style={{ padding: '3px', border: '1px solid black', textAlign: 'center', width: '23%' }}>Average Selling Price</td>
                            <td style={{ padding: '3px', border: '1px solid black', textAlign: 'center', width: '15%'}}>Revenue</td>  
                        </tr>

                        <tr style={{ height: '10px' }}></tr> 

                        <tr >
                          <td colSpan="4" style={{ padding: '3px', border: '1px solid black', color: 'white', background: '#082464', textAlign: 'center' }}>
                              <strong>AC Parts Breakdown </strong>
                          </td>
                        </tr>
                        <tr>
                            <td style={{ padding: '3px', border: '1px solid black', width: '50%'}}>AC Part</td>  
                            <td style={{ padding: '3px', border: '1px solid black', textAlign: 'center', width: '12%' }}>Units Sold</td>  
                            <td style={{ padding: '3px', border: '1px solid black', textAlign: 'center', width: '23%' }}>Average Selling Price</td>
                            <td style={{ padding: '3px', border: '1px solid black', textAlign: 'center', width: '15%'}}>Revenue</td>  
                        </tr>

                        <tr style={{ height: '10px' }}></tr> 


                        <tr>
                          <td colSpan="4" style={{ padding: '9px', border: '1px solid black', color: 'white', background: '#082464', textAlign: 'center' }}>
                              <strong>*** END OF REPORT *** </strong>
                          </td>
                        </tr>

                    </tbody>
                </Table>
            </Card>

       

            <button className="mt-4 btn w-40" onClick={handleSubmit} disabled={(loader)} style={{color: "white", backgroundColor: "#014c91"}}>
                
                {!loader?(
                    <span> {React.createElement(FaDownload, { size: 18, style: { marginRight: '5px' } })}  Download Forms </span>
                ):(
                  <span> <Spinner animation="border" size="sm" />  Downloading </span>
                )}
            
            </button>
           
           
        </div>
    );
};

export default SalesReport;
